spring:
    application:
        name: Schedules-Service
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3322/schedule-db
        username: root
        password: Quang13102006

    #jpa:
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect
                format_sql: true
server:
    port: 8088
